spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/secondHands
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

portone:
  api_key: "4861000422344416"
  api_secret: "DIBssYnCOBiI65A7TgJegtwWzz65npYz1BZS0sT3lUgKuA5rp5niYx328dBGuGHGVzu5ySRrgkCXtliF"